require File.expand_path('livro')
require File.expand_path('biblioteca')
require File.expand_path('relatorio')
require File.expand_path('curry/empresa')
require File.expand_path('curry/funcionario')
require File.expand_path('banco_de_arquivos')